# Generated by Django 5.2.17 on 2026-09-30 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('monthly_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / CEO / CMO'), ('MANAGER', 'Manager'), ('COUNSELLOR', 'Counsellor')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.office')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('GOOGLE', 'Google Ads'), ('WEBSITE', 'Website'), ('WALKIN', 'Walk-in'), ('DIRECT', 'Direct'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('academic_score', models.FloatField(default=60)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('COUNSELLING', 'Counselling'), ('APPLICATION', 'Application'), ('OFFER', 'Offer Received'), ('ENROLLED', 'Enrolled'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, limit_choices_to={'role': 'COUNSELLOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_leads', to='crm.employee')),
                ('assigned_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to='crm.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.office')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('admitted_on', models.DateField()),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('REMARK', 'Remark'), ('STATUS', 'Status Changed')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_probability', models.FloatField()),
                ('priority', models.CharField(max_length=10)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('model_version', models.CharField(default='logistic-v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='crm.lead')),
            ],
        ),
    ]
